### ISSUE TITLE
make `splitdef` return a `NamedTuple`

### ISSUE THREAD

**Issue by oxinabox** [MikeInnes/MacroTools.jl#116]
Dictionaries are slow, and allocating.
`splitdef` would be better as a `NamedTuple`

**Comment by MikeInnes** [comment]
To be fair, `Expr`s are also slow and allocating, so it's not that obvious to me that this is a benefit. If the code weren't more fiddly it'd be an easy decision. Are you seeing a real improvement from this?

**Comment by oxinabox** [comment]
You are right
there is nothing in it:

```
using MacroTools: splitdef
using BenchmarkTools

function testem()
    expr = :(
        function foo(x, y, z::Vector{T}) where T
            z[1] >= x + y
        end
    )
    return splitdef(expr)[:body]
end

@btime testem()

## Current
```
julia> @btime testem()
  343.263 μs (442 allocations: 28.98 KiB)
```


## With change
julia> @btime testem()
  404.812 μs (416 allocations: 26.28 KiB)
```

**Comment by cstjean** [comment]
`def.name` instead of `def[:name]` would be nicer though...
