### ISSUE TITLE
`isexpr` vs. `Meta.isexpr`

### ISSUE THREAD

**Issue by TotalVerb** [MikeInnes/MacroTools.jl#12]
Is there a reason why `MacroTools.isexpr` is distinct from `Base.Meta.isexpr`? They have slightly different interfaces, but on the whole it looks like they are trying to do the same thing.

**Comment by MikeInnes** [comment]
I think it basically boils down to: I don't want to use Base's version, and Base doesn't want to use mine. For one thing `Meta.isexpr` doesn't match on types, which is a hassle.

You're very welcome to try and make Base's version nicer but I warn you it'll be a struggle.

**Comment by TotalVerb** [comment]
Thanks for the explanation. Good enough for me.
