### ISSUE TITLE
Interpolating patterns in @capture

### ISSUE THREAD

**Issue by theogf** [MikeInnes/MacroTools.jl#137]
Is it possible to use `@capture` for generated patterns? MWE : 
```
pattern = Meta.parse("phi_(x_+y_)")
ex = :(f(a+b))
@capture(ex,$pattern) # returns true
@show x # returns x not defined
```
`@capture` returns true for the pattern showing it works, but then it leaves phi,x and y undefined...

**Comment by MikeInnes** [comment]
Yeah, this sorta works, but all the bindings need to be known to `@capture` at compile time. 

Easiest just to look at how `capture` is implemented; it calls a function version called `match` that returns a dictionary, so that will be the best way to do what you want here.

**Comment by theogf** [comment]
So by looking at what `capture` does internally it looks like `bs` is defined as `Any[]`, which is therefore not `nothing` and then returns `true`. Is it the behavior intended here?

And so if I understand correctly, should I do my own `@capture` macro, that would first interpret the `pattern` before running all the internals

**Comment by theogf** [comment]
I found my solution by calling `@eval` on top:
```
@eval @capture(ex,$pattern))
```
