### ISSUE TITLE
kw turns to =

### ISSUE THREAD

**Issue by bramtayl** [MikeInnes/MacroTools.jl#15]
I think there's a bug where a kw expression will turn into an assignment:

```julia
e = Expr(:kw, :a, 1)
enew = MacroTools.@match e begin
  a_ => a
  end

e.head != enew.head
```

**Comment by MikeInnes** [comment]
This happens intentionally as part of expression normalisation, the reason being that it makes it easier to destructure keyword expressions with a pattern. I think kw expressions can also pop up unexpectedly in places as well.

Is this causing a problem for you? What might help is to have some util function which un-normalises expressions, e.g. replacing `:=` with `:kw` in function calls etc.

**Comment by bramtayl** [comment]
I think what's going on in my code is that, if `:kw` is changed to `:=`,

```julia
DataFrame(a =1)
```
assigns `1` to `a`, and then passes `a` to `DataFrame`, so I'm actually getting

```julia
DataFrame(1)
```

**Comment by bramtayl** [comment]
I think the issue was that I was trying to use MacroTools recursively. The behavior now where `:kw` is changed to `:=` in the only the head of an expression seems reasonable. I think the julia macro parsers are doing the opposite.
