### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by davidanthoff** [MikeInnes/MacroTools.jl#17]
The currently tagged versions produces a very large number of deprecation warnings on julia 0.5, master seems fine. With the RC0 out for julia 0.5, it would be great if you could tag a version very soon so that we can clean up all the deprecation avalanche that is hitting users right now :)

**Comment by davidanthoff** [comment]
@MikeInnes bump, any chance you could do this soon? It would really help a lot of people that are trying to clean up the package situation for the julia 0.5 release.

**Comment by ranjanan** [comment]
@davidanthoff : https://github.com/JuliaLang/METADATA.jl/pull/5880
