### ISSUE TITLE
Error while loading MacroTools.jl and TaylorSeries.jl

### ISSUE THREAD

**Issue by PerezHz** [MikeInnes/MacroTools.jl#22]
Hi, 

In `julia 0.5.0-rc4+0` (OS X Yosemite 10.10.5), I'm having some trouble while loading `MacroTools` and `TaylorSeries`. At the REPL, I tried to run

``` julia
julia> using MacroTools, TaylorSeries
```

and everything worked fine; but I also tried to run

``` julia
julia> using TaylorSeries, MacroTools
```

and then I'm getting the following error:

``` julia
ERROR: TypeError: Tuple: in non-final parameter, expected Type{T}, got Type{Vararg{Int64,N}}
 in _include_from_serialized(::String) at ./loading.jl:150
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:187
 in _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:217
 in _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at /Users/Jorge/julia/julia-9c76c3e89a/lib/julia/sys.dylib:?
 in require(::Symbol) at ./loading.jl:371
 in require(::Symbol) at /Users/Jorge/julia/julia-9c76c3e89a/lib/julia/sys.dylib:?
```

I also tested for this issue in `julia 0.4.7-pre+3` but found no error there.

**Comment by lbenet** [comment]
I think this might be solved by a https://github.com/JuliaDiff/TaylorSeries.jl/pull/95. Can you please confirm?

**Comment by PerezHz** [comment]
Yes, it is now solved! Closing since this issue is fixed by JuliaDiff/TaylorSeries.jl#95
