### ISSUE TITLE
rmlines does not remove embedded line numbers

### ISSUE THREAD

**Issue by dpsanders** [MikeInnes/MacroTools.jl#24]
I had generated code that had line numbers embedded at all levels.
Here's a recursive version to strip them out, though I expect you can rewrite it in a much simpler way:
```julia
function rmlines!(ex)
        
    n = length(ex.args)
    i = 1

    while i <= n
        if isa(ex.args[i], Expr)
            
            if ex.args[i].head == :line
               
                deleteat!(ex.args, i)
                n -= 1
                continue
                
            else
                rmlines!(ex.args[i])

            end
        end
        
        i += 1
        
    end
end
```

**Comment by dpsanders** [comment]
Oh, I see that in fact `striplines` does this -- but is not exported?

**Comment by MikeInnes** [comment]
Ah yes this is `prewalk(rmlines, ex)` :) The reason it's not exported is because I've only used it internally in macrotools (for `prettify`) and don't generally recommend using it within macros, but if it's what you want there shouldn't be any issue using that function.

**Comment by dpsanders** [comment]
Got it, thanks!
