### ISSUE TITLE
Document and export `walk`, `prewalk` and `postwalk`

### ISSUE THREAD

**Issue by oxinabox** [MikeInnes/MacroTools.jl#34]
They are super useful,
but it is hard to see what they do, even by reading the source code.

**Comment by MikeInnes** [comment]
I'm wary of exporting these as they're quite generic names and won't play nicely with other possible implementations (e.g. for AbstractTrees or for DataFlow.jl). But docs would be a great idea, as would some notes in the readme on these utilities.

Do you mind taking a stab at this? Might be better coming from a fresh perspective.

**Comment by oxinabox** [comment]
I'm actually rather uncertain what they do myself.
I actually want the docs for me.

I've only used them by copy pasting your code...

**Comment by MikeInnes** [comment]
Ha, fair enough. You were basically right in the other issue, but I'll find some time to write this up.

**Comment by MikeInnes** [comment]
I finally updated the readme (this is a once-in-several-years event so we should probably throw a party or something). Let me know if this helps, and I can fix up anything that's incoherent right now.
