### ISSUE TITLE
Weird match behaviour over function definition

### ISSUE THREAD

**Issue by cstjean** [MikeInnes/MacroTools.jl#47]
On 0.6:
```julia
@capture(:(function foo(x) x+x end), function (fcall_ | fcall_) body_ end)  # true
@capture(:(function foo(x) x+x end), function (fcall_) body_ end)  # false
@capture(:(function foo(x) x+x end), function fcall_ body_ end)   # syntax error
```
I get that there isn't anything to be done about the last case, but it's weird that number one and number two aren't equivalent.

**Comment by MikeInnes** [comment]
(2) is just a weird parsing special case, it gets interpreted as a tuple of arguments (which makes sense outside of a match expression). Unfortunately, I don't see anything we can do about this, since the surface information is permanently lost.

```julia
julia> :(function (a) c end)
:(function (a,) # REPL[4], line 1:
        c
    end)
```

**Comment by cstjean** [comment]
That makes sense.
