### ISSUE TITLE
Could not capture import expression

### ISSUE THREAD

**Issue by ngphuoc** [MikeInnes/MacroTools.jl#58]
The following failed. Is there a way to support this capture pattern?
```julia
julia> ex=:(Base:cat,hcat,vcat)                            
:((Base:cat, hcat, vcat))                                  

julia> @capture(ex, M_:fs__)                               
false                                                      
```

**Comment by cstjean** [comment]
Your `ex` parses as a tuple of three expressions because it's range syntax. Either put an `import` in front of it to force import syntax, or use parentheses:

```julia
julia> ex=:(Base:(cat,hcat,vcat))
:(Base:(cat, hcat, vcat))

julia> @capture(ex, M_:fs_)
true
```

**Comment by ngphuoc** [comment]
I see, I missed the import keyword. I prefer the import syntax forcing since it looks more natural. Thanks a lot.
