### ISSUE TITLE
expression with | operator

### ISSUE THREAD

**Issue by Ken-B** [MikeInnes/MacroTools.jl#64]
I'm looking into using the `@formula` macro from the `StatsModels` package, which allows using the `|` operator. This is used e.g. by `MixedModels` for random effect in groups.

However, I can't seem to parse it. Is it interfering with the usage of `|` for MacroTools optionality?

MWE
```julia
@capture :(y~x|e~z) (left_|right_)
```
where the variable `right` comes out empty.

Thanks!

**Comment by MikeInnes** [comment]
Correct; you can fix this by inserting a literal pipe symbol into the capture expression (also known as curly-haired-man `$:|`).

```julia
julia> @capture(:(x|y), $:|(a_,b_)); (a,b)
(:x, :y)
```
That said, note that this probably isn't doing what you want in the original expression: `:(y~x|e~z) == :(y ~ (x | e ~ z))`.

**Comment by Ken-B** [comment]
Thank you for making my day! I had not heard of the curly-haired man before :D 

Thanks also for the explanation and correction to my MWE, I'll look for a different formula style then.
