### ISSUE TITLE
Allow for determinmism in the alias_gensyms

### ISSUE THREAD

**Issue by philtomson** [MikeInnes/MacroTools.jl#70]
We're having a heck of a time debugging ONNX.jl given that it uses MacroTools.alias_gensyms in generating it's output. The problem is that given the same inputs, we always get a different output (alias_gensyms replaces gensysms with animal names). This makes it very difficult to compare two different outputs from ONNX.jl.

I see where the "problem" is (from our perspective), it's in the __init__ function in src/MacroTools.jl, specifically, this line:
`Compat.Random.shuffle!(animals)`

**Comment by cstjean** [comment]
Couldn't you `srand(1)` before importing/using MacroTools.jl?

**Comment by philtomson** [comment]
Could do that, but it requires users of MacroTools to know a lot about the internals of MacroTools

Why is the randomisation there?

**Comment by MikeInnes** [comment]
Closed by #72
