### ISSUE TITLE
bizzare match failure for macros in type assertions

### ISSUE THREAD

**Issue by peterahrens** [MikeInnes/MacroTools.jl#75]
MacroTools can't match macros when they appear in the type assertions in function calls. This seems like a crazy issue, but a key macro in my package depended on this functionality and now something has changed with the latest julia build and things fail. Any ideas as to why this match failure would happen?
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.5246 (2018-05-29 13:27 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 082be9a (8 days old master)
|__/                   |  x86_64-apple-darwin17.5.0

(v0.7) pkg> up MacroTools
  Updating registry at `~/.julia/registries/Uncurated`
  Updating git-repo `https://github.com/JuliaRegistries/Uncurated.git`
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v0.7/Manifest.toml`
 [no changes]

julia> using MacroTools

julia> x = :(foo(x::@bar(qux))).args[2].args[2]
:(#= REPL[3]:1 =# @bar qux)

julia> :(@bar(qux))
:(#= REPL[4]:1 =# @bar qux)

julia> x.head
:macrocall

julia> :(@bar(qux)).head
:macrocall

julia> x.args
3-element Array{Any,1}:
 Symbol("@bar")
 :(#= REPL[3]:1 =#)
 :qux

julia> :(@bar(qux)).args
3-element Array{Any,1}:
 Symbol("@bar")
 :(#= REPL[8]:1 =#)
 :qux

julia> @capture(x, @bar(qux))
false

julia> @capture(:(@bar(qux)), @bar(qux))
true
```
EDIT: It appears that this has something to do with line number nodes getting passed as arguments to macros. I rolled a custom solution for myself, but I'll dig into this sometime when I have more time. I don't think this has anything to do with the type assertions at all now.

**Comment by MikeInnes** [comment]
Yeah, I assume that at some point we end up comparing the line number arguments for equality, and that's where this falls down. I think it'd be easy enough to add a method overload somewhere to catch this.

**Comment by peterahrens** [comment]
I suppose that we could assume all linenumber nodes are equal, but I wonder if there would be unintended consequences. Do people want to match on linenumber nodes? Is there even a way to express them in the @capture macro without a quotenode?

**Comment by BenLauwens** [comment]
Hi

I have the same problem. [ResumableFunctions](https://github.com/BenLauwens/ResumableFunctions.jl) replaces an `@yield` macro with some expression involving a `return`. Can you share your custom solution? In my use case all linenumber nodes in the macro can be considered equal.
Thanks

Ben

**Comment by peterahrens** [comment]
Sure! I was looking for all instances of `@hyperspecialize(x)' called with a single argument. I used separate functions to detect this call and then get the argument. It looks like this:

```
_is_hyperspecialize(X) = false
function _is_hyperspecialize(X::Expr)
  return X.head == :macrocall &&
    length(X.args) == 3 &&
    X.args[1] == Symbol("@hyperspecialize")
end

function _get_hyperspecialize(X)
  @assert _is_hyperspecialize(X)
  return X.args[3]
end
```
This passes a battery of tests but they weren't exaustively focused on this macro so let me know if this solution fails you. 


If you're looking for just `@yeild` without any arguments, You would probably want something like:
```
_is_yeild(X) = false
function _is_yeild(X::Expr)
  return X.head == :macrocall &&
    length(X.args) == 2 &&
    X.args[1] == Symbol("@yeild")
end
```
Here's what I see from the REPL.
```julia
julia> :(@yeild).head
:macrocall

julia> :(@yeild).args
2-element Array{Any,1}:
 Symbol("@yeild")
 :(#= REPL[2]:1 =#)
```
