### ISSUE TITLE
don't use exceptions to implement `ismatch` and `trymatch`

### ISSUE THREAD

**Issue by JeffBezanson** [MikeInnes/MacroTools.jl#81]
This is causing https://github.com/JuliaLang/julia/issues/28221. At least for APIs that return a result instead of exposing `MatchError`, the package should use return values instead of exceptions.

**Comment by MikeInnes** [comment]
Yeah this has always been a performance issue. I think we need a little Rust-style `@try` macro to make it simple to do the backtracking here without exceptions.

**Comment by cstjean** [comment]
Matching is essentially interpreted in MacroTools, right? I wonder how hard it would be to directly macroexpand patterns like `foo(x_, 2)` into `if ex.head==:call && ex.args[1] == :foo && ...` On Lisp had an implementation for Common Lisp.

**Comment by MikeInnes** [comment]
Right, the core matching machinery is a function of both a template and an expression to match. We could do something smarter there, but it essentially means having two separate implementations of matching, and the performance benefit will not likely be that great. Really it's just the use of throw/catch that's adding the extra order of magnitude hit here.

**Comment by cstjean** [comment]
> it essentially means having two separate implementations of matching

Why? If we had a compiled version, we could ditch the interpreted one.

> the performance benefit will not likely be that great

I wonder about that. MacroTools is pretty ubiquitous these days.

**Comment by MikeInnes** [comment]
Perhaps. At the very least it's part of the API now (you can also splice runtime expressions into the pattern). But that might be infrequently-used enough that we can just get rid of it.

I could see us getting something like 2x better with a compiled version, especially on simple cases like that one. Once you get to slurping and such though, there's always going to be quite a lot of dynamic dispatch, backtracking etc. and it's not that likely to have a noticeable impact of precompilation.

I'm happy to be proven wrong though. We could always have a very simple compiler that bails out to the interpreter, and then gradually expand that and remove the current implementation as we go along – just needs someone willing to hack on it.
