### ISSUE TITLE
Documents and demos

### ISSUE THREAD

**Issue by Roger-luo** [MikeInnes/MacroTools.jl#83]
Hi Mike,

do you want to set up a Documenter.jl doc? I can make a PR for this.

Bests,
Roger

**Comment by MikeInnes** [comment]
Sure, I think now's a good time to start having real docs for this.

**Comment by Roger-luo** [comment]
could you set up a travis CI for me pls? I will need it for Documenter.

**Comment by o314** [comment]
By the way, the current [docs/utilities.md](https://github.com/MikeInnes/MacroTools.jl/edit/master/docs/src/utilities.md#L37-L40)

```julia
function name{params}(args; kwargs)::rtype where {whereparams}
   body
end
```

is not up to date with current function form after v1.0

> The syntax for parametric methods, function f{T}(x::T), has been changed to function f(x::T) where {T} [(#11310)](https://github.com/JuliaLang/julia/issues/11310).

**Comment by MikeInnes** [comment]
Would be great to have a patch to fix that.

I'll close this issue for now since we have docs up.
