### ISSUE TITLE
Union not working with simple comparisons

### ISSUE THREAD

**Issue by dpsanders** [MikeInnes/MacroTools.jl#9]
Just discovered this very nice package, thanks!
The following works:
```
julia> using MacroTools

julia> ex = :(x <= 1)
:(x <= 1)

julia> @match ex begin
       a_ <= b_  => (a,b)
       end
(:x,1)
```
but this union doesn't:
```
julia> @match ex begin
       (a_ <= b_ | a_ < b_) => (a,b)
       end 
```
(returns nothing).
Am I misunderstanding something?

**Comment by dpsanders** [comment]
Ah, apparently I need more parentheses:
```
julia> @match ex begin
       ((a_ <= b_) | (a_ < b_)) => (a,b)
       end
(:x,1)
```

**Comment by dpsanders** [comment]
Sorry for the noise.

**Comment by MikeInnes** [comment]
Precedence, precedence :)

No worries, enjoy the package and let me know how else I can help.
